on: 
  push:
    branches:
      - develop
name: Deploy dev
jobs:
  dev-web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.DEV_BASE_URL }}

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Build Project
      run: |
        yarn install
        yarn build
    
    - name: Deploy over FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: eliaschenker.com
        username: ${{ secrets.DEV_FTP_USERNAME }}
        password: ${{ secrets.DEV_FTP_PASSWORD }}
        server-dir: /
        local-dir: ./.output/public/
